### ISSUE TITLE
StackOverflowException MProfiles

### ISSUE THREAD

**Issue by karlovm** [AlphaBs/MinecraftLauncherLibrary#12]
If the folder, named 1.15.2 with files 1.15.2.jar and 1.15.2.json (it's renamed optifine 1.15.2), exists
   MProfile profile = MProfile.FindProfile(infos, "1.15.2"); returns System.StackOverflowException and i can't catch it.

**Comment by AlphaBs** [comment]
Why do you want to do that?
It is impossible to set name of Optifine or Forge profile to its base profile.

Because Optifine and Forge cannot be launched alone, so Launcher try to load base profile (in this case 1.15.2), according to `inheritFrom` property of profile json file.
But 1.15.2 is also Optifine profile, so launcher loads 1.15.2 profile again and again.

**Comment by karlovm** [comment]
Is it possible to trown an exception instead programm crash?

**Comment by AlphaBs** [comment]
1.1.1 released. now throw IOException.
